-- Persistence 통합 테스트 전용 Migration이다. src/integrationTest/resources에만 존재하며
-- Production Migration(src/main/resources/db/migration)과 별개다. GETI 비즈니스 Domain을
-- 암시하지 않는 중립적인 이름을 사용한다.
CREATE TABLE persistence_probe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(255) NOT NULL
);
