-- Search 도메인(Issue #69)의 색인 실패 재처리, 전체 재색인 실행 이력 Table이다. 검색 결과
-- 자체(Job 요약 Document)는 PostgreSQL이 아니라 Elasticsearch에 저장하므로 여기에는 없다.

-- 공고 색인(UPSERT) 또는 색인 제거(DELETE)가 Elasticsearch 오류로 실패했을 때만 생성되는
-- 재시도 대상 Row다. 성공하면 이 Row를 지운다(이력이 아니라 "현재 미해결 실패" 목록).
-- next_retry_at이 NULL이면 최대 재시도 횟수를 넘겨 더 이상 재시도하지 않는 영구 실패를 뜻하고,
-- 값이 있으면 그 시각 이후 재시도 대상이다(별도 상태 Column 없이 next_retry_at만으로 판단한다).
CREATE TABLE search_index_failures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    operation VARCHAR(20) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMP,
    last_error VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_search_index_failures_job UNIQUE (job_id),
    CONSTRAINT ck_search_index_failures_attempt_count CHECK (attempt_count >= 0)
);

CREATE INDEX idx_search_index_failures_next_retry
    ON search_index_failures (next_retry_at);

-- 개발자가 POST /api/v1/admin/search-actions로 트리거하는 전체 재색인 1회 실행 이력이다.
-- Collector의 collection_runs(Issue #62)와 동일한 이유로 범용 async_operations Table을
-- 재사용하지 않고 전용 Table을 둔다(operation 도메인은 아직 Service/공개 계약이 없음,
-- docs/architecture/erd.md의 "collector가 operation의 Enum을 재사용하는 이유" 참고 — 다만
-- 이번에는 값 집합도 다르지 않지만 사용처 자체가 없어 동일한 판단을 따른다).
CREATE TABLE search_reindex_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    total_count BIGINT,
    success_count BIGINT,
    failure_count BIGINT,
    error_message VARCHAR(1000),
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_search_reindex_runs_counts CHECK (
        total_count IS NULL OR (total_count >= 0 AND success_count >= 0 AND failure_count >= 0)
    )
);

-- 이미 실행 중인 재색인이 있는지(중복 요청 차단, 409 REINDEX_ALREADY_RUNNING) 확인하는 조회 기준.
CREATE INDEX idx_search_reindex_runs_status ON search_reindex_runs (status);

-- Application 계층의 existsByStatusIn 확인과 INSERT 사이에는 DB 잠금이 없어(TOCTOU), 거의
-- 동시에 들어온 두 요청이 모두 통과해 PENDING/RUNNING Row가 2개 이상 생길 수 있다(PR #70
-- Review 반영). 활성 상태(PENDING/RUNNING) Row가 항상 1건 이하이도록 DB 제약으로 강제한다 —
-- WHERE 절을 만족하는 모든 Row가 상수 표현식(TRUE)에 대해 같은 값을 가지므로, 이 Index는
-- "활성 Row는 최대 1건"이라는 의미가 된다. 두 번째 INSERT는 Unique 제약 위반으로 실패하고
-- SearchReindexServiceImpl이 이를 REINDEX_ALREADY_RUNNING(409)으로 변환한다.
CREATE UNIQUE INDEX uk_search_reindex_runs_active_singleton
    ON search_reindex_runs ((true))
    WHERE status IN ('PENDING', 'RUNNING');
