-- Application 도메인 개인 신청 양식(Form) 기능(Epic #75, Phase 1 - Issue #76). 교사·개발자가
-- 개인 소유로 재사용하는 신청 양식 템플릿이다. 공고나 프로그램에 종속되어 생성되지 않고, 공고와의
-- 연결은 이후 Phase(공고-양식 연결)에서 별도로 다룬다. 이 Migration은 그 연결을 포함하지 않는다.
--
-- forms: 양식 자체(소유자, 이름, 상태, 현재 버전 번호)
-- form_versions: 버전별 필드 구조 스냅샷(불변, Update/삭제 없음). 필드 배열은 schema_data JSONB에
--   그대로 저장한다(jobs.target_condition, job_applications.answers와 동일한 관례 — 구조화된
--   검증/파싱은 Application 계층이 담당).
CREATE TABLE forms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_member_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    form_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    current_version INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_forms_owner_member FOREIGN KEY (owner_member_id)
        REFERENCES members (id),
    CONSTRAINT ck_forms_current_version CHECK (current_version > 0)
);

CREATE INDEX idx_forms_owner_member_id ON forms (owner_member_id);

CREATE TABLE form_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id BIGINT NOT NULL,
    version INTEGER NOT NULL,
    schema_data JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_form_versions_form_version UNIQUE (form_id, version),
    CONSTRAINT fk_form_versions_form FOREIGN KEY (form_id)
        REFERENCES forms (id),
    CONSTRAINT ck_form_versions_version CHECK (version > 0)
);
