-- Inquiry 도메인을 1:N 답변 구조로 재구성한다.
--
-- 배경: V2에서 만든 inquiries 테이블은 문의 하나에 답변 하나만 담는 구조였다(answer,
-- answered_by_member_id 컬럼). 그러나 실제 API 명세(GETI Inquiry 도메인 개발 요구사항 20절)는
-- 하나의 문의가 여러 답변을 가질 수 있다고 정의해 inquiry_answers 테이블을 새로 만들고 기존
-- 단일 답변 컬럼은 제거한다(사용자 확인 완료).
--
-- 기존 데이터가 있을 가능성에 대비해, 컬럼을 지우기 전에 answer가 채워진 행을 먼저
-- inquiry_answers로 옮긴다 — 옮길 행이 없으면(현재까지 Inquiry API/Service가 없어 실제로
-- 없을 가능성이 높다) 아래 INSERT는 아무 것도 하지 않고 안전하게 통과한다.

-- ============================================================
-- 1. inquiry_answers 테이블 생성
-- ============================================================
CREATE TABLE inquiry_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_id BIGINT NOT NULL,
    author_member_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_inquiry_answers_inquiry FOREIGN KEY (inquiry_id)
        REFERENCES inquiries (id),
    CONSTRAINT fk_inquiry_answers_author_member FOREIGN KEY (author_member_id)
        REFERENCES members (id)
);

CREATE INDEX idx_inquiry_answers_inquiry_id_created_at
    ON inquiry_answers (inquiry_id, created_at);

-- ============================================================
-- 2. 기존 단일 답변 데이터 이관
-- ============================================================
-- answer가 있고 작성자(answered_by_member_id)를 알 수 있는 행만 옮긴다. created_at은 기존
-- 단일 답변이 실제로 등록된 시점을 최대한 보존하기 위해 answered_at -> updated_at -> created_at
-- 순으로 대체값을 찾는다. inquiries.answered_at 자체는 새 구조에서도 "최초 답변 시각"이라는
-- 같은 의미로 계속 쓰이므로 이 단계에서 다시 계산하거나 closed_at 값을 참고하지 않는다.
INSERT INTO inquiry_answers (inquiry_id, author_member_id, content, created_at)
SELECT id, answered_by_member_id, answer, COALESCE(answered_at, updated_at, created_at)
FROM inquiries
WHERE answer IS NOT NULL
  AND answered_by_member_id IS NOT NULL;

-- ============================================================
-- 3. inquiries 테이블 재구성
-- ============================================================
-- 이관을 마친 단일 답변 컬럼(answer, answered_by_member_id)과, 새 구조에서 상태(status=CLOSED)만
-- 으로 표현되는 closed_at을 제거한다. PostgreSQL은 컬럼에 종속된 FK 제약을 DROP COLUMN 시점에
-- 자동으로 함께 제거한다.
--
-- discord_message_id/discord_error_message는 이번에 제거하지 않는다. Discord 공통 계약
-- (discord_deliveries 테이블, PENDING/PROCESSING/DELIVERED/FAILED)이 아직 저장소에 없어 당장
-- 대체할 곳이 없고, Program 도메인이 Phase 7 교체 예정으로 남긴 경고 주석과 동일한 방식으로
-- Deprecated 상태로만 유지한다(사용자 확인 완료). 신규 Inquiry 로직은 이 두 컬럼을 사용하지 않는다.
ALTER TABLE inquiries
    DROP COLUMN answer,
    DROP COLUMN answered_by_member_id,
    DROP COLUMN closed_at;

ALTER TABLE inquiries
    ADD COLUMN assignee_member_id BIGINT,
    ADD CONSTRAINT fk_inquiries_assignee_member FOREIGN KEY (assignee_member_id)
        REFERENCES members (id) ON DELETE SET NULL;

-- ============================================================
-- 4. 목록/필터 조회에 필요한 복합 Index 추가
-- ============================================================
-- 기존 idx_inquiries_author_member_id(author_member_id)/idx_inquiries_status(status)는 아래
-- 복합 Index의 선두 Column과 겹쳐 중복이지만, 이번 PR 범위를 좁히기 위해 정리하지 않고 그대로
-- 둔다(사용자 확인 완료).
CREATE INDEX idx_inquiries_author_member_created ON inquiries (author_member_id, created_at);
CREATE INDEX idx_inquiries_status_created ON inquiries (status, created_at);
CREATE INDEX idx_inquiries_type_created ON inquiries (type, created_at);
CREATE INDEX idx_inquiries_assignee_status ON inquiries (assignee_member_id, status);