-- Recommendation R3(Issue #152): 회원별 추천 기능 ON/OFF 설정을 저장한다. 기존 Migration(V22
-- 이하)은 수정하지 않는다.
--
-- recommendation_preferences: member_job_preferences(member_id, job_id 복합 PK)와 달리 회원
-- 1명당 최대 1행만 존재하므로(추천 기능 전체 ON/OFF, Job 단위가 아님) 별도 Table로 분리했다.
-- Row가 없으면 "설정한 적 없음"으로 간주하고 Application(RecommendationServiceImpl)이
-- default(false)로 해석한다 -- Row를 Lazy하게 만들어(ON으로 바꾸는 시점에만 Insert) 기존
-- 회원 전체를 Backfill할 필요가 없다.
CREATE TABLE recommendation_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_recommendation_preferences_member_id UNIQUE (member_id),
    CONSTRAINT fk_recommendation_preferences_member FOREIGN KEY (member_id)
        REFERENCES members (id) ON DELETE CASCADE
);
