-- Recommendation Notion 계약 정합성 작업(Issue #155): 기존 Migration(V23 이하)은 수정하지
-- 않는다.
--
-- member_job_preferences: Notion API 명세(GET/POST/DELETE
-- /api/v1/me/recommendation-exclusions)가 "관심 없음" 설정을 Long exclusionId를 가진 독립
-- Resource로 요구한다. 기존 복합 PK(member_id, job_id)는 그 자체로는 안정적인 Long 식별자를
-- 제공하지 못해(가짜 Hash/임의 숫자 변환 금지, docs/ai/security-policy.md 원칙과 동일한 이유로
-- 이번 작업 지시에서도 명시적으로 금지) Surrogate PK(id)로 교체한다. (member_id, job_id) 조합의
-- 유일성은 별도 UNIQUE 제약으로 그대로 보존해 기존 Hard Filter/Bookmark Row Lifecycle 동작에는
-- 영향이 없다.
--
-- PostgreSQL은 기존 Row가 있는 Table에 `GENERATED BY DEFAULT AS IDENTITY` Column을 추가하면
-- 그 즉시 순차 값으로 Backfill한다(SERIAL Column 추가와 동일한 동작, PostgreSQL 10+) — 별도
-- Sequence를 만들고 UPDATE로 수동 채울 필요가 없다.
ALTER TABLE member_job_preferences ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE member_job_preferences DROP CONSTRAINT pk_member_job_preferences;
ALTER TABLE member_job_preferences ADD CONSTRAINT pk_member_job_preferences PRIMARY KEY (id);
ALTER TABLE member_job_preferences ADD CONSTRAINT uk_member_job_preferences_member_job
    UNIQUE (member_id, job_id);

-- exclusion_created_at: Notion 계약(관심 없음 등록 Resource의 createdAt)이 요구하는 "관심 없음이
-- 설정된 시각"이다. 기존 updated_at은 bookmarked 변경 등 이 Row의 다른 변경으로도 갱신되므로
-- exclusion 자체의 설정 시각과 다를 수 있어 별도 Column으로 분리한다. exclusion이 NULL이면 함께
-- NULL이다(해제 시 같이 지운다, Application에서 관리).
ALTER TABLE member_job_preferences ADD COLUMN exclusion_created_at TIMESTAMP;

-- 기존에 이미 exclusion이 설정되어 있던 Row는 정확한 최초 설정 시각을 알 수 없으므로
-- updated_at을 최선의 근사값으로 Backfill한다(문서화된 가정, PR 본문 참고).
UPDATE member_job_preferences SET exclusion_created_at = updated_at WHERE exclusion IS NOT NULL;
