-- Recommendation R4(Issue #160): 회원 1명의 마지막 일일 추천 Generation 실행 상태를 저장한다.
-- 기존 Migration(V24 이하)은 수정하지 않는다.
--
-- recommendation_generation_states: Daily Scheduler가 회원 1명을 처리할 때마다
-- GENERATING -> READY/EMPTY 또는 GENERATING -> FAILED로 이 Row 하나를 갱신한다(회원당 최대
-- 1행). Recommendation(추천 결과 Row 자체)만으로는 EMPTY(계산은 성공했지만 결과 없음)와
-- FAILED(계산 자체가 실패)를 구분할 수 없어 별도 Table로 분리했다. generated_at은 마지막으로
-- 성공한 시각, last_failure_at은 마지막으로 실패한 시각이며 둘 다 서로를 지우지 않는다(과거
-- 성공/실패 이력을 함께 보존).
CREATE TABLE recommendation_generation_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    generated_at TIMESTAMP,
    last_failure_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_recommendation_generation_states_member_id UNIQUE (member_id),
    CONSTRAINT fk_recommendation_generation_states_member FOREIGN KEY (member_id)
        REFERENCES members (id) ON DELETE CASCADE
);
