-- ============================================================
-- Portfolio Domain Phase 1 (Portfolio Core)
-- ============================================================
-- V2(초기 Domain Persistence 골격)의 portfolio 스키마를 Portfolio 도메인 요구사항 문서의
-- 확정 계약에 맞춰 재구성한다. Portfolio는 아직 Use Case/Controller가 없고 운영 데이터도
-- 없으므로 컬럼 재구성이 안전하다. 이미 병합된 V2 파일은 수정하지 않고 새 버전으로만 바꾼다.
--
-- 확정된 결정(사용자 승인):
--   1) 대상 학생은 `target_condition` JSONB가 아니라 별도 `portfolio_request_targets` 테이블에
--      구체적 studentId 집합으로 저장한다(요구사항 §5/§19 — 미제출 학생 현황 계산의 근간).
--   2) 제출 기간은 `dueAt` 하나만 사용한다(요구사항 §25/§38 — startAt 임의 추가 금지).
--      기존 `submission_ended_at`을 `due_at`으로 옮기고 `submission_started_at`은 제거한다.
--   3) 제출 필수 자료 정책(`allow_file`/`allow_url`)은 Product Decision(§15/§39-5)이 확정되기
--      전까지 요청 스키마로 굳히지 않으므로 제거한다.

-- ------------------------------------------------------------
-- 1. portfolio_request_targets (신규) — 수합 요청의 실제 제출 대상 학생
-- ------------------------------------------------------------
CREATE TABLE portfolio_request_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    student_member_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_portfolio_request_targets_request_student UNIQUE (request_id, student_member_id),
    CONSTRAINT fk_portfolio_request_targets_request FOREIGN KEY (request_id)
        REFERENCES portfolio_requests (id),
    CONSTRAINT fk_portfolio_request_targets_student FOREIGN KEY (student_member_id)
        REFERENCES members (id)
);

CREATE INDEX idx_portfolio_request_targets_request_id ON portfolio_request_targets (request_id);
CREATE INDEX idx_portfolio_request_targets_student_member_id
    ON portfolio_request_targets (student_member_id);

-- ------------------------------------------------------------
-- 2. portfolio_requests 재구성 — dueAt 계약으로 정렬
-- ------------------------------------------------------------
ALTER TABLE portfolio_requests RENAME COLUMN submission_ended_at TO due_at;
ALTER TABLE portfolio_requests DROP COLUMN submission_started_at;
ALTER TABLE portfolio_requests DROP COLUMN target_condition;
ALTER TABLE portfolio_requests DROP COLUMN allow_file;
ALTER TABLE portfolio_requests DROP COLUMN allow_url;

CREATE INDEX idx_portfolio_requests_due_at ON portfolio_requests (due_at);
