-- GETI 최신 최소 19개 Table 핵심 Domain Schema.
-- 과거 27개 Table 설계는 폐기되었으며 이 Migration에서 복원하지 않는다.
--
-- 이 Source Set(src/main)의 실제 첫 Migration이지만 V1이 아니라 V2로 시작한다.
-- src/integrationTest/resources/db/migration/V1__create_persistence_probe.sql이 이미
-- V1을 사용 중이고, integrationTest 실행 시에는 main과 integrationTest의 resources가
-- 같은 classpath(db/migration)로 합쳐져 Flyway가 두 위치를 구분하지 못한다(Version 충돌).
-- persistence_probe Migration은 이미 병합된 Test 전용 파일이라 수정하지 않고, 대신 이
-- 새 Migration의 Version을 V2로 시작해 충돌을 피한다.
--
-- 생성 순서는 FK 의존성을 따른다. members와 files는 서로를 참조하는 순환 관계라
-- members를 먼저 만들고(profile_image_file_id는 이 시점에 FK 없이 컬럼만 추가),
-- files를 만든 뒤 ALTER TABLE로 members -> files FK를 뒤늦게 추가한다.
--
-- FK 삭제 정책(ON DELETE) 원칙:
--   - 같은 Aggregate에 종속된 자식/연결 Row(member_roles, refresh_tokens,
--     member_job_preferences, job_ai_analyses, recommendations, notifications)는
--     부모가 사라지면 함께 의미를 잃으므로 CASCADE.
--   - 작성자/업로더/승인자처럼 이력 성격이 강하지 않은 Nullable 참조는 SET NULL로
--     레코드 자체는 보존한다(files.uploader_member_id, members.profile_image_file_id,
--     companies.logo_file_id, jobs.created_by_member_id/manager_member_id,
--     inquiries.answered_by_member_id, async_operations.*, audit_logs.actor_member_id).
--   - 지원/신청/제출/문의처럼 보존해야 하는 이력이면서 NOT NULL FK인 경우는 상위
--     Row를 실수로 지우면 이력이 함께 사라지는 것을 막기 위해 명시적 ON DELETE를
--     선언하지 않는다(PostgreSQL 기본값 NO ACTION = 참조가 남아있으면 삭제 차단).

-- ============================================================
-- 1. members
-- ============================================================
CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oauth_provider VARCHAR(30) NOT NULL,
    oauth_subject VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(100),
    status VARCHAR(30) NOT NULL,
    academic_status VARCHAR(30),
    cohort INTEGER,
    grade INTEGER,
    department VARCHAR(30),
    profile_image_file_id BIGINT,
    phone_number VARCHAR(30),
    introduction VARCHAR(1000),
    github_url VARCHAR(500),
    profile_public BOOLEAN NOT NULL,
    majors JSONB,
    skills JSONB,
    desired_positions JSONB,
    rejection_reason VARCHAR(1000),
    approved_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    withdrawn_at TIMESTAMP,
    CONSTRAINT uk_members_oauth_provider_subject UNIQUE (oauth_provider, oauth_subject),
    CONSTRAINT uk_members_email UNIQUE (email),
    CONSTRAINT ck_members_grade CHECK (grade IS NULL OR grade BETWEEN 1 AND 3)
);

-- ============================================================
-- 2. files
-- ============================================================
CREATE TABLE files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploader_member_id BIGINT,
    owner_type VARCHAR(100) NOT NULL,
    owner_id BIGINT NOT NULL,
    object_key VARCHAR(1000) NOT NULL,
    original_name VARCHAR(500) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    size_bytes BIGINT NOT NULL,
    contains_personal_information BOOLEAN NOT NULL,
    expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_files_uploader_member FOREIGN KEY (uploader_member_id)
        REFERENCES members (id) ON DELETE SET NULL,
    CONSTRAINT ck_files_size_bytes CHECK (size_bytes >= 0)
);

CREATE INDEX idx_files_uploader_member_id ON files (uploader_member_id);
CREATE INDEX idx_files_owner ON files (owner_type, owner_id);

-- members.profile_image_file_id -> files.id (순환 FK, files 생성 이후 추가)
ALTER TABLE members
    ADD CONSTRAINT fk_members_profile_image_file FOREIGN KEY (profile_image_file_id)
        REFERENCES files (id) ON DELETE SET NULL;

-- ============================================================
-- 3. member_roles
-- ============================================================
CREATE TABLE member_roles (
    member_id BIGINT NOT NULL,
    role VARCHAR(30) NOT NULL,
    granted_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_member_roles PRIMARY KEY (member_id, role),
    CONSTRAINT fk_member_roles_member FOREIGN KEY (member_id)
        REFERENCES members (id) ON DELETE CASCADE
);

-- ============================================================
-- 4. refresh_tokens
-- ============================================================
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    device_identifier VARCHAR(255),
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_member FOREIGN KEY (member_id)
        REFERENCES members (id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_member_id ON refresh_tokens (member_id);

-- ============================================================
-- 5. companies
-- ============================================================
CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    logo_file_id BIGINT,
    description TEXT,
    industry VARCHAR(255),
    address VARCHAR(1000),
    website_url VARCHAR(1000),
    type VARCHAR(30) NOT NULL,
    source VARCHAR(255),
    mou_status VARCHAR(30) NOT NULL,
    mou_started_on DATE,
    mou_ended_on DATE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_companies_logo_file FOREIGN KEY (logo_file_id)
        REFERENCES files (id) ON DELETE SET NULL
);

CREATE INDEX idx_companies_logo_file_id ON companies (logo_file_id);

-- ============================================================
-- 6. jobs
-- ============================================================
CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    created_by_member_id BIGINT,
    manager_member_id BIGINT,
    type VARCHAR(30) NOT NULL,
    application_method VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    title VARCHAR(500) NOT NULL,
    body_markdown TEXT,
    source_name VARCHAR(255),
    external_job_id VARCHAR(255),
    external_url VARCHAR(2000),
    discord_channel_key VARCHAR(255),
    recruitment_started_at TIMESTAMP,
    recruitment_ended_at TIMESTAMP,
    target_grade INTEGER,
    capacity INTEGER,
    first_come_served BOOLEAN NOT NULL,
    required_skills JSONB,
    application_form_schema JSONB,
    view_count BIGINT NOT NULL,
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_jobs_company FOREIGN KEY (company_id)
        REFERENCES companies (id),
    CONSTRAINT fk_jobs_created_by_member FOREIGN KEY (created_by_member_id)
        REFERENCES members (id) ON DELETE SET NULL,
    CONSTRAINT fk_jobs_manager_member FOREIGN KEY (manager_member_id)
        REFERENCES members (id) ON DELETE SET NULL,
    CONSTRAINT ck_jobs_view_count CHECK (view_count >= 0),
    CONSTRAINT ck_jobs_capacity CHECK (capacity IS NULL OR capacity > 0),
    CONSTRAINT ck_jobs_target_grade CHECK (target_grade IS NULL OR target_grade BETWEEN 1 AND 3)
);

CREATE INDEX idx_jobs_company_id ON jobs (company_id);
CREATE INDEX idx_jobs_created_by_member_id ON jobs (created_by_member_id);
CREATE INDEX idx_jobs_manager_member_id ON jobs (manager_member_id);
CREATE INDEX idx_jobs_status ON jobs (status);
CREATE INDEX idx_jobs_status_published_at ON jobs (status, published_at);
-- 외부 수집 공고 중복 방지: source_name/external_job_id가 둘 다 있는 Row만 유일해야 하고
-- 내부 공고(둘 다 NULL)는 여러 개 있어도 된다 -> Partial Unique Index.
CREATE UNIQUE INDEX uk_jobs_source_external_id ON jobs (source_name, external_job_id)
    WHERE source_name IS NOT NULL AND external_job_id IS NOT NULL;

-- ============================================================
-- 7. member_job_preferences
-- ============================================================
CREATE TABLE member_job_preferences (
    member_id BIGINT NOT NULL,
    job_id BIGINT NOT NULL,
    bookmarked BOOLEAN NOT NULL,
    exclusion VARCHAR(30),
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_member_job_preferences PRIMARY KEY (member_id, job_id),
    CONSTRAINT fk_member_job_preferences_member FOREIGN KEY (member_id)
        REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT fk_member_job_preferences_job FOREIGN KEY (job_id)
        REFERENCES jobs (id) ON DELETE CASCADE
);

CREATE INDEX idx_member_job_preferences_job_id ON member_job_preferences (job_id);

-- ============================================================
-- 8. job_ai_analyses (job_id가 jobs.id를 공유하는 PK)
-- ============================================================
CREATE TABLE job_ai_analyses (
    job_id BIGINT PRIMARY KEY,
    status VARCHAR(30) NOT NULL,
    summary TEXT,
    eligibility_summary TEXT,
    extracted_skills JSONB,
    reanalysis_count INTEGER NOT NULL,
    error_message TEXT,
    requested_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    CONSTRAINT fk_job_ai_analyses_job FOREIGN KEY (job_id)
        REFERENCES jobs (id) ON DELETE CASCADE,
    CONSTRAINT ck_job_ai_analyses_reanalysis_count CHECK (reanalysis_count BETWEEN 0 AND 3)
);

-- ============================================================
-- 9. recommendations
-- ============================================================
CREATE TABLE recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    job_id BIGINT NOT NULL,
    recommendation_date DATE NOT NULL,
    score NUMERIC(7, 4) NOT NULL,
    suitability VARCHAR(30) NOT NULL,
    reasons JSONB,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_recommendations_member_job_date UNIQUE (member_id, job_id, recommendation_date),
    CONSTRAINT fk_recommendations_member FOREIGN KEY (member_id)
        REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT fk_recommendations_job FOREIGN KEY (job_id)
        REFERENCES jobs (id) ON DELETE CASCADE
);

CREATE INDEX idx_recommendations_member_date ON recommendations (member_id, recommendation_date);
CREATE INDEX idx_recommendations_job_id ON recommendations (job_id);

-- ============================================================
-- 10. job_applications
-- ============================================================
CREATE TABLE job_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    applicant_member_id BIGINT NOT NULL,
    attempt_number INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL,
    contact_email VARCHAR(255) NOT NULL,
    contact_phone VARCHAR(30),
    answers JSONB NOT NULL,
    status_reason TEXT,
    submitted_at TIMESTAMP,
    forwarded_at TIMESTAMP,
    withdrawn_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_job_applications_job_applicant_attempt UNIQUE (job_id, applicant_member_id, attempt_number),
    CONSTRAINT fk_job_applications_job FOREIGN KEY (job_id)
        REFERENCES jobs (id),
    CONSTRAINT fk_job_applications_applicant_member FOREIGN KEY (applicant_member_id)
        REFERENCES members (id),
    CONSTRAINT ck_job_applications_attempt_number CHECK (attempt_number > 0)
);

CREATE INDEX idx_job_applications_applicant_member_id ON job_applications (applicant_member_id);
CREATE INDEX idx_job_applications_status ON job_applications (status);

-- ============================================================
-- 11. programs
-- ============================================================
CREATE TABLE programs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_member_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    title VARCHAR(500) NOT NULL,
    body_markdown TEXT,
    location VARCHAR(500),
    event_started_at TIMESTAMP,
    event_ended_at TIMESTAMP,
    application_started_at TIMESTAMP,
    application_ended_at TIMESTAMP,
    capacity INTEGER,
    application_form_schema JSONB,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_programs_created_by_member FOREIGN KEY (created_by_member_id)
        REFERENCES members (id),
    CONSTRAINT ck_programs_capacity CHECK (capacity IS NULL OR capacity > 0)
);

CREATE INDEX idx_programs_created_by_member_id ON programs (created_by_member_id);
CREATE INDEX idx_programs_status ON programs (status);
CREATE INDEX idx_programs_application_period ON programs (application_started_at, application_ended_at);

-- ============================================================
-- 12. program_applications
-- ============================================================
-- 동일 회원의 재신청을 하나의 Row 상태 전환으로 볼지, 여러 Row(이력)로 볼지가
-- 아직 확정되지 않아(AGENTS.md DECISION_REQUIRED) UNIQUE(program_id, applicant_member_id)를
-- 추가하지 않았다. 사용자 확인 후 필요하면 별도 Migration으로 추가한다.
CREATE TABLE program_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL,
    applicant_member_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    answers JSONB,
    applied_at TIMESTAMP NOT NULL,
    canceled_at TIMESTAMP,
    CONSTRAINT fk_program_applications_program FOREIGN KEY (program_id)
        REFERENCES programs (id),
    CONSTRAINT fk_program_applications_applicant_member FOREIGN KEY (applicant_member_id)
        REFERENCES members (id)
);

CREATE INDEX idx_program_applications_program_id ON program_applications (program_id);
CREATE INDEX idx_program_applications_applicant_member_id ON program_applications (applicant_member_id);

-- ============================================================
-- 13. portfolio_requests
-- ============================================================
CREATE TABLE portfolio_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_member_id BIGINT NOT NULL,
    title VARCHAR(500) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL,
    target_condition JSONB NOT NULL,
    submission_started_at TIMESTAMP NOT NULL,
    submission_ended_at TIMESTAMP NOT NULL,
    allow_file BOOLEAN NOT NULL,
    allow_url BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_portfolio_requests_created_by_member FOREIGN KEY (created_by_member_id)
        REFERENCES members (id)
);

CREATE INDEX idx_portfolio_requests_created_by_member_id ON portfolio_requests (created_by_member_id);
CREATE INDEX idx_portfolio_requests_status ON portfolio_requests (status);

-- ============================================================
-- 14. portfolio_submissions
-- ============================================================
CREATE TABLE portfolio_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    portfolio_url VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    submitted_at TIMESTAMP,
    CONSTRAINT uk_portfolio_submissions_request_member UNIQUE (request_id, member_id),
    CONSTRAINT fk_portfolio_submissions_request FOREIGN KEY (request_id)
        REFERENCES portfolio_requests (id),
    CONSTRAINT fk_portfolio_submissions_member FOREIGN KEY (member_id)
        REFERENCES members (id)
);

CREATE INDEX idx_portfolio_submissions_member_id ON portfolio_submissions (member_id);

-- ============================================================
-- 15. notifications
-- ============================================================
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_member_id BIGINT NOT NULL,
    type VARCHAR(100) NOT NULL,
    title VARCHAR(500) NOT NULL,
    content TEXT NOT NULL,
    resource_type VARCHAR(100),
    resource_id BIGINT,
    is_read BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    read_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_notifications_recipient_member FOREIGN KEY (recipient_member_id)
        REFERENCES members (id) ON DELETE CASCADE
);

CREATE INDEX idx_notifications_recipient_read_created
    ON notifications (recipient_member_id, is_read, created_at);

-- ============================================================
-- 16. inquiries
-- ============================================================
CREATE TABLE inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_member_id BIGINT NOT NULL,
    answered_by_member_id BIGINT,
    type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    title VARCHAR(500) NOT NULL,
    content TEXT NOT NULL,
    answer TEXT,
    discord_message_id VARCHAR(255),
    discord_error_message TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    answered_at TIMESTAMP,
    closed_at TIMESTAMP,
    CONSTRAINT fk_inquiries_author_member FOREIGN KEY (author_member_id)
        REFERENCES members (id),
    CONSTRAINT fk_inquiries_answered_by_member FOREIGN KEY (answered_by_member_id)
        REFERENCES members (id) ON DELETE SET NULL
);

CREATE INDEX idx_inquiries_author_member_id ON inquiries (author_member_id);
CREATE INDEX idx_inquiries_status ON inquiries (status);

-- ============================================================
-- 17. job_collection_runs
-- ============================================================
CREATE TABLE job_collection_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL,
    new_count INTEGER NOT NULL,
    updated_count INTEGER NOT NULL,
    failed_count INTEGER NOT NULL,
    error_summary TEXT,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    CONSTRAINT ck_job_collection_runs_new_count CHECK (new_count >= 0),
    CONSTRAINT ck_job_collection_runs_updated_count CHECK (updated_count >= 0),
    CONSTRAINT ck_job_collection_runs_failed_count CHECK (failed_count >= 0)
);

CREATE INDEX idx_job_collection_runs_source_started ON job_collection_runs (source_name, started_at);

-- ============================================================
-- 18. async_operations
-- ============================================================
CREATE TABLE async_operations (
    id UUID PRIMARY KEY,
    requested_by_member_id BIGINT,
    type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    progress_percent INTEGER NOT NULL,
    target_type VARCHAR(100),
    target_id BIGINT,
    result_file_id BIGINT,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    expires_at TIMESTAMP,
    CONSTRAINT fk_async_operations_requested_by_member FOREIGN KEY (requested_by_member_id)
        REFERENCES members (id) ON DELETE SET NULL,
    CONSTRAINT fk_async_operations_result_file FOREIGN KEY (result_file_id)
        REFERENCES files (id) ON DELETE SET NULL,
    CONSTRAINT ck_async_operations_progress_percent CHECK (progress_percent BETWEEN 0 AND 100)
);

CREATE INDEX idx_async_operations_status ON async_operations (status);
CREATE INDEX idx_async_operations_requested_by_member_id ON async_operations (requested_by_member_id);

-- ============================================================
-- 19. audit_logs
-- ============================================================
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_member_id BIGINT,
    action VARCHAR(255) NOT NULL,
    target_type VARCHAR(100) NOT NULL,
    target_id BIGINT,
    request_id UUID,
    changed_data JSONB,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_logs_actor_member FOREIGN KEY (actor_member_id)
        REFERENCES members (id) ON DELETE SET NULL
);

CREATE INDEX idx_audit_logs_target ON audit_logs (target_type, target_id);
CREATE INDEX idx_audit_logs_actor_member_id ON audit_logs (actor_member_id);
