-- Issue #220: my-profile 화면이 실제로 렌더링하는 복수 링크(블로그, 포트폴리오 등)를 저장할 Table을
-- 추가한다. 기존 members.github_url(V2)은 하위 호환을 위해 그대로 유지하고, 이 Table은 그 외의
-- 임의 개수 링크(label + url)를 별도로 저장한다.
--
-- 개수/이름 상한(member_majors, member_tech_stacks 없음)이 정해져 있지 않은 자유 목록이라
-- member_majors/member_tech_stacks(V4)의 복합키 Join Table 대신, 순서(order)를 가진 독립 Row
-- 목록이 필요해 Surrogate Key를 쓰는 Row 기반 Table로 설계했다.
--
-- ============================================================
-- member_profile_links
-- ============================================================
CREATE TABLE member_profile_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    label VARCHAR(100) NOT NULL,
    url VARCHAR(2000) NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_member_profile_links_member FOREIGN KEY (member_id)
        REFERENCES members (id) ON DELETE CASCADE
);

-- 내 프로필/공개 프로필 조회는 항상 member_id로 조회해 표시 순서(display_order)대로 정렬한다.
CREATE INDEX idx_member_profile_links_member_order
    ON member_profile_links (member_id, display_order);
