-- 푸시 기기 등록·해제 및 푸시 알림 설정 API(Issue #189, Notification Phase 4)를 위한 Table 2개를
-- 추가한다. Provider(FCM/APNs) 실제 발송 연동은 이 Migration 범위가 아니다(Issue #190).
--
-- notification_devices
--   device_key는 안정적인 기기/앱 설치 식별자이고, push_token은 FCM/APNs Token(만료·재발급 가능)
--   이라 별도 Column으로 분리한다(Issue #189 확정 계약). device_key는 (member_id, device_key)
--   조합이 아니라 Global Unique다 -- 같은 기기를 다른 회원이 등록하면 그 회원으로 소유권이
--   이전되는 것을 기본 정책으로 하기 때문이다(Application 계층이 INSERT ... ON CONFLICT
--   (device_key) DO UPDATE로 원자적으로 처리, NotificationDeviceRepository.upsert 참고).
--   member_id가 사라지면 그 회원 명의의 기기 등록도 의미가 없으므로 member_job_preferences 등과
--   같은 CASCADE 정책을 따른다.
--
-- notification_settings
--   회원당 push_enabled 하나만 있다(NotificationType별로 나누지 않는다, Issue #189 확정 계약).
--   job_ai_analyses(job_id를 공유 PK로 사용)와 같은 방식으로 member_id를 그대로 PK로 쓴다 -- 이
--   Table은 회원 1명당 정확히 0개 또는 1개 Row만 가능한 순수 1:1 관계라 별도 대리 PK가 필요 없다.
--   pushEnabled=false여도 이 Table은 등록된 기기(Row)를 지우지 않는다 -- 그 정책은
--   notification_devices에 영향을 주지 않고, Push 발송 여부 판단(#190)에서만 이 값을 읽는다.

CREATE TABLE notification_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    device_key VARCHAR(255) NOT NULL,
    push_token VARCHAR(1000) NOT NULL,
    platform VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_notification_devices_device_key UNIQUE (device_key),
    CONSTRAINT fk_notification_devices_member FOREIGN KEY (member_id)
        REFERENCES members (id) ON DELETE CASCADE
);

CREATE INDEX idx_notification_devices_member_id ON notification_devices (member_id);

CREATE TABLE notification_settings (
    member_id BIGINT PRIMARY KEY,
    push_enabled BOOLEAN NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_notification_settings_member FOREIGN KEY (member_id)
        REFERENCES members (id) ON DELETE CASCADE
);
