-- 기술 스택 메타데이터(tech_stacks) Table.
-- V2의 19개 핵심 Domain Schema에는 포함되지 않았던 신규 조회용 Table이다.

-- ============================================================
-- 20. tech_stacks
-- ============================================================
CREATE TABLE tech_stacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(30) NOT NULL,
    CONSTRAINT uk_tech_stacks_name UNIQUE (name)
);
