-- 전공(majors) 메타데이터와 Member의 전공/기술 스택 선택을 N:M Join Table로 정규화한다.
-- 기존 members.majors/members.skills(jsonb 자유 문자열)는 majorId/techStackId 기반 관계로
-- 대체되어 더 이상 필요하지 않으므로 함께 제거한다.

-- ============================================================
-- 21. majors
-- ============================================================
CREATE TABLE majors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_majors_name UNIQUE (name)
);

-- ============================================================
-- 22. member_majors
-- ============================================================
CREATE TABLE member_majors (
    member_id BIGINT NOT NULL,
    major_id BIGINT NOT NULL,
    CONSTRAINT pk_member_majors PRIMARY KEY (member_id, major_id),
    CONSTRAINT fk_member_majors_member FOREIGN KEY (member_id)
        REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT fk_member_majors_major FOREIGN KEY (major_id)
        REFERENCES majors (id)
);

-- ============================================================
-- 23. member_tech_stacks
-- ============================================================
CREATE TABLE member_tech_stacks (
    member_id BIGINT NOT NULL,
    tech_stack_id BIGINT NOT NULL,
    CONSTRAINT pk_member_tech_stacks PRIMARY KEY (member_id, tech_stack_id),
    CONSTRAINT fk_member_tech_stacks_member FOREIGN KEY (member_id)
        REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT fk_member_tech_stacks_tech_stack FOREIGN KEY (tech_stack_id)
        REFERENCES tech_stacks (id)
);

-- members.majors/members.skills는 V2에서 추가된 이후 이를 읽거나 쓰는 Service/Repository가
-- 한 번도 존재하지 않았다(전체 코드베이스 확인 완료). 다만 로컬/개발 환경에서 수동으로 값이
-- 들어갔을 가능성까지 배제할 수는 없으므로, 실제로 남아있는 데이터가 있으면 자동 삭제 대신
-- Migration 자체를 실패시켜 데이터 유실을 막는다.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM members WHERE majors IS NOT NULL OR skills IS NOT NULL) THEN
        RAISE EXCEPTION 'members.majors 또는 members.skills에 남아있는 데이터가 있어 Migration을 중단합니다. Backfill 후 다시 실행하세요.';
    END IF;
END $$;

ALTER TABLE members DROP COLUMN majors;
ALTER TABLE members DROP COLUMN skills;
