-- 전공(majors) 메타데이터와 Member의 전공/기술 스택 선택을 N:M Join Table로 정규화한다.
-- 기존 members.majors/members.skills(jsonb 자유 문자열)는 majorId/techStackId 기반 관계로
-- 대체되어 더 이상 필요하지 않으므로 함께 제거한다.

-- ============================================================
-- 21. majors
-- ============================================================
CREATE TABLE majors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_majors_name UNIQUE (name)
);

-- ============================================================
-- 22. member_majors
-- ============================================================
CREATE TABLE member_majors (
    member_id BIGINT NOT NULL,
    major_id BIGINT NOT NULL,
    CONSTRAINT pk_member_majors PRIMARY KEY (member_id, major_id),
    CONSTRAINT fk_member_majors_member FOREIGN KEY (member_id)
        REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT fk_member_majors_major FOREIGN KEY (major_id)
        REFERENCES majors (id)
);

-- ============================================================
-- 23. member_tech_stacks
-- ============================================================
CREATE TABLE member_tech_stacks (
    member_id BIGINT NOT NULL,
    tech_stack_id BIGINT NOT NULL,
    CONSTRAINT pk_member_tech_stacks PRIMARY KEY (member_id, tech_stack_id),
    CONSTRAINT fk_member_tech_stacks_member FOREIGN KEY (member_id)
        REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT fk_member_tech_stacks_tech_stack FOREIGN KEY (tech_stack_id)
        REFERENCES tech_stacks (id)
);

ALTER TABLE members DROP COLUMN majors;
ALTER TABLE members DROP COLUMN skills;
