-- Collector 도메인 실제 기능 구현(Issue #62)을 위한 Table.
--
-- job_collection_runs(V2, Foundation ERD Placeholder)는 이미 CoreDomainSchemaIntegrationTest가
-- 참조하고 있어 그대로 둔다. collection_runs/collection_run_errors는 실제 운영 API가 요구하는
-- source 참조, action, partial_quality_count 등을 담는 별도 Table이다.
--
-- FK 삭제 정책은 V2의 원칙을 따른다: collection_run_errors는 collection_runs에 종속된 이력이라
-- CASCADE, collection_runs -> job_sources는 이력 성격이 강한 NOT NULL 참조라 명시적 ON DELETE를
-- 선언하지 않는다(참조가 남아있으면 삭제를 차단하는 기본값 유지, 현재 job_sources를 삭제하는
-- API도 없다).

-- ============================================================
-- job_sources
-- ============================================================
CREATE TABLE job_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code VARCHAR(30) NOT NULL,
    name VARCHAR(255) NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    approval_status VARCHAR(30) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    daily_request_limit INTEGER,
    last_collected_at TIMESTAMP,
    last_success_at TIMESTAMP,
    last_failure_at TIMESTAMP,
    last_error VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_job_sources_source_code UNIQUE (source_code),
    CONSTRAINT ck_job_sources_daily_request_limit CHECK (daily_request_limit IS NULL OR daily_request_limit > 0)
);

-- ============================================================
-- collection_runs
-- ============================================================
CREATE TABLE collection_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL,
    action VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    total_count INTEGER NOT NULL DEFAULT 0,
    success_count INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    partial_quality_count INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_collection_runs_source FOREIGN KEY (source_id)
        REFERENCES job_sources (id),
    CONSTRAINT ck_collection_runs_counts CHECK (
        total_count >= 0 AND success_count >= 0 AND failure_count >= 0 AND partial_quality_count >= 0
    )
);

CREATE INDEX idx_collection_runs_source_started ON collection_runs (source_id, started_at);
CREATE INDEX idx_collection_runs_status ON collection_runs (status);

-- ============================================================
-- collection_run_errors
-- ============================================================
CREATE TABLE collection_run_errors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    external_job_id VARCHAR(255),
    code VARCHAR(100) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    missing_fields VARCHAR(1000),
    occurred_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_collection_run_errors_run FOREIGN KEY (run_id)
        REFERENCES collection_runs (id) ON DELETE CASCADE
);

CREATE INDEX idx_collection_run_errors_run_id ON collection_run_errors (run_id);
